name: resuing terraform deploy 

on:
  workflow_dispatch:

jobs:
  terraform:
        uses: ./.github/workflows/reusable.yaml
        with:
          workflow_input: ' input while calling reusable workflow' 
