name: Terraform Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
        uses: ./.github/workflows/reusable-terraform-deploy.yaml
        with:
          terraform_version: '1.5.1'  # Specify the desired Terraform version
          aws_region: 'us-east-1'

