name: Terraform Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
        uses: ./.github/workflows/reusable-terraform-deploy
        with:
          terraform_version: '1.5.1'  # Specify the desired Terraform version
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: 'us-east-1'

